---
- hosts: all
  become: no
  tasks:
    - name: Ensure .bashrc exists
      copy:
        content: ""
        dest: "~/.bashrc"
        force: no
        mode: '0644'

    - name: Add or replace PS1 prompt
      lineinfile:
        path: "~/.bashrc"
        regexp: '^export PS1='
        line: 'export PS1="\[\033[95m\]\u@\h \[\033[32m\]\W\[\033[33m\] [\$(git symbolic-ref --short HEAD 2>/dev/null)]\[\033[00m\]\$ "'
        state: present

    - name: Add .local/bin to PATH at the beginning
      lineinfile:
        path: "~/.bashrc"
        regexp: '^export PATH=\$HOME/\.local/bin:'
        line: 'export PATH=$HOME/.local/bin:$PATH'
        state: present

    - name: Add /sbin and /usr/sbin to PATH
      lineinfile:
        path: "~/.bashrc"
        regexp: '^export PATH=.*:/sbin:/usr/sbin'
        line: 'export PATH=$PATH:/sbin:/usr/sbin'
        state: present

    - name: Set DISPLAY
      lineinfile:
        path: "~/.bashrc"
        regexp: '^export DISPLAY='
        line: 'export DISPLAY=:0'
        state: present

    - name: Debug .bashrc content
      shell: cat ~/.bashrc
      register: bashrc_content
      changed_when: false

    - name: Display .bashrc content
      debug:
        var: bashrc_content.stdout_lines
