---
- hosts: all
  become: no
  tasks:
    - name: Backup existing .bashrc
      copy:
        src: "~/.bashrc"
        dest: "~/.bashrc.backup"
        remote_src: yes
        force: no

    - name: Create a new .bashrc with custom configurations
      copy:
        content: |
          # Existing bash configuration
          # ~/.bashrc: executed by bash(1) for non-login shells.
          
          # If not running interactively, don't do anything
          case $- in
              *i*) ;;
                *) return;;
          esac

          # Preserve existing history settings
          HISTCONTROL=ignoreboth
          shopt -s histappend
          HISTSIZE=1000
          HISTFILESIZE=2000

          # Check window size after each command
          shopt -s checkwinsize

          # Custom Prompt and Path Configurations
          export PS1="\[\033[95m\]\u@\h \[\033[32m\]\W\[\033[33m\] [\$(git symbolic-ref --short HEAD 2>/dev/null)]\[\033[00m\]\$ "
          export PATH=$HOME/.local/bin:$HOME/bin:$PATH
          export PATH=$PATH:/sbin:/usr/sbin
          export DISPLAY=:0
        dest: "~/.bashrc"
        mode: '0644'

    - name: Verify .bashrc configuration
      shell: 
        cmd: |
          source ~/.bashrc
          echo "PS1 Setting:"
          echo "$PS1"
          echo "---"
          echo "PATH:"
          echo "$PATH" | tr ':' '\n'
          echo "---"
          echo "DISPLAY:"
          echo "$DISPLAY"
      register: bashrc_verification
      changed_when: false
      args:
        executable: /bin/bash

    - name: Display verification results
      debug:
        var: bashrc_verification.stdout_lines
