---
- hosts: all  # You can specify specific hosts or host groups
  become: no  # Run as the current user
  vars:
    bashrc_additions:
      - line: 'export PS1="\[\033[95m\]\u@\h \[\033[32m\]\W\[\033[33m\] [\$(git symbolic-ref --short HEAD 2>/dev/null)]\[\033[00m\]\$ "'
        regexp: '^export PS1='
      - line: 'export PATH=$HOME/.local/bin:$PATH'
        regexp: '^export PATH=\$HOME/\.local/bin:\$PATH'
      - line: 'export PATH=$PATH:/sbin:/usr/sbin'
        regexp: '^export PATH=\$PATH:/sbin:/usr/sbin'
      - line: 'export DISPLAY=:0'
        regexp: '^export DISPLAY=:0'

  tasks:
    - name: Ensure .bashrc exists
      copy:
        content: ""
        dest: "~/.bashrc"
        force: no  # Only create if it doesn't exist
        mode: '0644'

    - name: Add lines to .bashrc if not already present
      lineinfile:
        path: "~/.bashrc"
        line: "{{ item.line }}"
        regexp: "{{ item.regexp }}"
        insertafter: EOF
      loop: "{{ bashrc_additions }}"
      when: item.line is defined and item.regexp is defined
