---
- hosts: all
  become: no
  tasks:
    - name: Append custom PS1 prompt
      lineinfile:
        path: "~/.bashrc"
        line: 'export PS1="\[\033[95m\]\u@\h \[\033[32m\]\W\[\033[33m\] [\$(git symbolic-ref --short HEAD 2>/dev/null)]\[\033[00m\]\$ "'
        state: present
        insertafter: EOF

    - name: Append .local/bin to PATH
      lineinfile:
        path: "~/.bashrc"
        line: 'export PATH=$HOME/.local/bin:$PATH'
        state: present
        insertafter: EOF

    - name: Append /sbin and /usr/sbin to PATH
      lineinfile:
        path: "~/.bashrc"
        line: 'export PATH=$PATH:/sbin:/usr/sbin'
        state: present
        insertafter: EOF

    - name: Append DISPLAY
      lineinfile:
        path: "~/.bashrc"
        line: 'export DISPLAY=:0'
        state: present
        insertafter: EOF

    - name: Verify .bashrc modifications
      shell: 
        cmd: |
          grep 'export PS1=' ~/.bashrc
          grep 'export PATH=$HOME/.local/bin:$PATH' ~/.bashrc
          grep 'export PATH=$PATH:/sbin:/usr/sbin' ~/.bashrc
          grep 'export DISPLAY=:0' ~/.bashrc
      register: bashrc_check
      changed_when: false
      ignore_errors: true

    - name: Display verification results
      debug:
        var: bashrc_check.stdout_lines
