---
- name: Test sudo permissions
  hosts: web_servers
  become: yes
  
  tasks:
  - name: Test sudo
    command: whoami
    register: whoami_result
  
  - name: Display result
    debug:
      var: whoami_result.stdout
