---
- name: Diagnostic sudo test
  hosts: web_servers
  gather_facts: yes
  
  tasks:
  - name: Test passwordless sudo
    shell: "sudo -n id"
    ignore_errors: yes
    register: passwordless_sudo
    
  - name: Show result of passwordless sudo test
    debug:
      var: passwordless_sudo.stdout
      
  - name: Create a test file in /root
    shell: "echo 'test' | sudo -S tee /root/ansible_test_file.txt"
    register: test_file
    ignore_errors: yes
    
  - name: Show result of test file creation
    debug:
      var: test_file
