---
- name: Direct sudo test
  hosts: web_servers
  become: yes
  
  tasks:
  - name: Run a command that must be root
    shell: "id"
    register: id_output
    
  - name: Display output
    debug:
      var: id_output.stdout
