---
- hosts: web_servers
  become: true
  tasks:
    - name: Update apt cache (Debian/Ubuntu)
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Upgrade all packages (Debian/Ubuntu)
      apt:
        upgrade: dist
        force_apt_get: yes
      when: ansible_os_family == "Debian"

    - name: Update dnf cache (Rocky Linux 8+)
      dnf:
        update_cache: yes
      when: ansible_distribution == "Rocky" and ansible_distribution_major_version|int >= 8

    - name: Upgrade all packages (Rocky Linux 8+)
      dnf:
        name: '*'
        state: latest
      when: ansible_distribution == "Rocky" and ansible_distribution_major_version|int >= 8

    - name: Update yum cache (Rocky Linux 7 and other RHEL family)
      yum:
        update_cache: yes
      when: (ansible_distribution == "Rocky" and ansible_distribution_major_version|int < 8) or 
            (ansible_os_family == "RedHat" and ansible_distribution != "Fedora" and ansible_distribution != "Rocky")

    - name: Upgrade all packages (Rocky Linux 7 and other RHEL family)
      yum:
        name: '*'
        state: latest
      when: (ansible_distribution == "Rocky" and ansible_distribution_major_version|int < 8) or 
            (ansible_os_family == "RedHat" and ansible_distribution != "Fedora" and ansible_distribution != "Rocky")

    - name: Update dnf cache (Fedora)
      dnf:
        update_cache: yes
      when: ansible_distribution == "Fedora"

    - name: Upgrade all packages (Fedora)
      dnf:
        name: '*'
        state: latest
      when: ansible_distribution == "Fedora"

    - name: Update pacman cache (Arch Linux)
      pacman:
        update_cache: yes
      when: ansible_distribution == "Archlinux"

    - name: Upgrade all packages (Arch Linux)
      pacman:
        upgrade: yes
      when: ansible_distribution == "Archlinux"

    - name: Update zypper cache (openSUSE)
      zypper:
        update_cache: yes
      when: ansible_os_family == "Suse"

    - name: Upgrade all packages (openSUSE)
      zypper:
        name: '*'
        state: latest
      when: ansible_os_family == "Suse"
